### ISSUE TITLE
Error when running example with ruby 2.0.0-p648

### ISSUE THREAD

**Issue by njh** [chadrem/workers#11]
Hi,

I have just been trying out your gem, but got an error when I ran the following example:

```ruby
require 'worker'

# Initialize a worker pool.
pool = Workers::Pool.new(:on_exception => proc { |e|
  puts "A worker encountered an exception: #{e.class}: #{e.message}"
})

# Perform some work in the background.
100.times do
  pool.perform do
    sleep(rand(3))
    raise 'sad face' if rand < 0.5
    puts "Hello world from thread #{Thread.current.object_id}"
  end
end

# Wait up to 30 seconds for the workers to cleanly shutdown (or forcefully kill them).
pool.dispose(30) do
  puts "Worker thread #{Thread.current.object_id} is shutting down."
end
```

The error was:

```
/Users/njh/.rbenv/versions/2.0.0-p648/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require': /Users/njh/.rbenv/versions/2.0.0-p648/lib/ruby/gems/2.0.0/gems/worker-0.6.0/lib/worker.rb:91: syntax error, unexpected keyword_rescue, expecting keyword_end (SyntaxError)
      rescue Exception => ex
            ^
/Users/njh/.rbenv/versions/2.0.0-p648/lib/ruby/gems/2.0.0/gems/worker-0.6.0/lib/worker.rb:99: syntax error, unexpected '.'
    @thread&.kill
             ^
        from /Users/njh/.rbenv/versions/2.0.0-p648/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
        from /Users/njh/.rbenv/versions/2.0.0-p648/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
        from worker-test.rb:28:in `<main>'
```

Is this a ruby 2 compatibly bug?

**Comment by chadrem** [comment]
I recommend you try the latest version of the gem (0.6.1) and see if it works. Also Ruby 2.0.0 is unsupported. I recommend you try 2.2.x or newer. I'll update the readme.

**Comment by njh** [comment]
Thanks for the fast response. The problem was actually because I stayed up too late and typed `worker` instead of `workers`! Which happens to have a very similar version number. If you install the right gem, it works fine 😞

I am using ruby 2.0.0, because that is the default ruby that comes with CentOS 7 / RHEL 7 but I will think about upgrading.
